version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: security_ai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hackathon2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - security_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - security_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Juice Shop - Target Application
  juiceshop:
    image: bkimminich/juice-shop:latest
    ports:
      - "3000:3000"
    networks:
      - security_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI - Custom SIEM + AI Agents
  fastapi:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:hackathon2024@postgres:5432/security_ai
      - REDIS_URL=redis://redis:6379
      - JUICESHOP_URL=http://juiceshop:3000
      - JUICESHOP_SOURCE=/app/juiceshop-source
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./backend:/app
      - ./juiceshop-source:/app/juiceshop-source:ro
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - security_net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend - React Dashboard
  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - fastapi
    networks:
      - security_net
    command: sh -c "npm install && npm start"
    stdin_open: true
    tty: true

networks:
  security_net:
    driver: bridge

volumes:
  postgres_data:
